### 3. Factorizaciones y Eigenvalores

#### Factorizaciones

Las factorizaciones descomponen matrices para resolver problemas más eficientemente.

* LU:

In [1]:
using LinearAlgebra
A = [2.0 1.0; 1.0 3.0]
lu_A = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
2×2 Matrix{Float64}:
 1.0  0.0
 0.5  1.0
U factor:
2×2 Matrix{Float64}:
 2.0  1.0
 0.0  2.5

#### ¿Qué es la Descomposición LU?

La descomposición LU descompone una matriz cuadrada A en tres componentes:

* L: Matriz triangular inferior (con unos en la diagonal).
* U: Matriz triangular superior.
* P: Matriz de permutación (para evitar divisiones por cero durante la descomposición).

La relación es:

$$PA=LU$$


In [2]:
# Define una matriz A
A = [1 2; 3 4]

# Realiza la descomposición LU
F = lu(A)

# Accede a los componentes
L = F.L    # Matriz triangular inferior
U = F.U    # Matriz triangular superior
P = F.P    # Vector de permutación (equivale a P*A = L*U)

# Reconstructura A usando P, L, U
A_reconstructed = P' * L * U  # P' es la transpuesta de P

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

* Cholesky (para matrices simétricas definidas positivas):

In [3]:
chol_A = cholesky(A' * A)

Cholesky{Float64, Matrix{Float64}}
U factor:
2×2 UpperTriangular{Float64, Matrix{Float64}}:
 3.16228  4.42719
  ⋅       0.632456

#### Eigenvalores y Eigenvectores

Los eigenvalores son útiles para analizar estabilidad en sistemas de potencia.

In [4]:
A = [1.0 2.0; 3.0 4.0]
evals = eigvals(A)
evecs = eigvecs(A)
println("Eigenvalores: ", evals)
println("Eigenvectores: ", evecs)

Eigenvalores: [-0.3722813232690143, 5.372281323269014]
Eigenvectores: [-0.8245648401323938 -0.4159735579192842; 0.5657674649689923 -0.9093767091321241]


### 4. Aplicaciones en Sistemas de Potencia

En sistemas de potencia, el álgebra lineal se usa para:

* Matriz de Incidencia: Representa la conexión entre nodos y líneas.

* Matriz de Admitancia (Y-bus): Relaciona corrientes y voltajes.

* Flujo DC: Resuelve sistemas lineales basados en ángulos nodales y flujos.

Ejemplo: Construcción de Matriz de Incidencia

In [8]:
using DataFrames

num_n = 3  # Número de nodos
num_l = 2  # Número de líneas
lines = DataFrame(FROM=[1, 2], TO=[2, 3])
A = zeros(num_n, num_n)  # Matriz de incidencia
for i in 1:num_l
    k = lines.FROM[i]
    m = lines.TO[i]
    A[k, i] = 1
    A[m, i] = -1
end

display(A)
# Output:
# [1.0  0.0
#  -1.0 1.0
#  0.0 -1.0]

3×3 Matrix{Float64}:
  1.0   0.0  0.0
 -1.0   1.0  0.0
  0.0  -1.0  0.0