#### **Ejercicio Práctico**

**Objetivo:** Aplicar álgebra lineal en un problema de sistemas de potencia.

Tarea:

* Crea una matriz de incidencia para un sistema con 4 nodos y 3 líneas (`FROM: [1, 2, 3], TO: [2, 3, 4]`).
* Crea un vector de flujos de potencia en las líneas: `[50.0, 60.0, 70.0]`.
* Calcula el balance neto de potencia en cada nodo usando la matriz de incidencia y el vector de flujos.

Resuelve un sistema lineal simple para encontrar los ángulos nodales (( \theta )) suponiendo una matriz de susceptancia diagonal ( `B = [2.0, 2.0, 2.0, 2.0]` ) y un vector de inyecciones de potencia `[100.0, -50.0, -30.0, -20.0]`.

In [2]:
using DataFrames
using LinearAlgebra

# Create el DataFrame con los datos de ejemplo (FROM y TO)
lines = DataFrame(FROM = [1, 2, 3], TO = [2, 3, 4])
nodes = DataFrame(node = [1,2,3,4])
display(lines)

3×2 DataFrame
 Row │ FROM   TO    
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2
   2 │     2      3
   3 │     3      4

In [3]:
# 1. Creando la matriz de incidencia
A = zeros(Int, size(nodes, 1), size(lines, 1))
for i in 1:length(lines.FROM)
    k = lines.FROM[i]
    m = lines.TO[i]
    A[k, i] = 1
    A[m, i] = -1
end
display(A)

4×3 Matrix{Int64}:
  1   0   0
 -1   1   0
  0  -1   1
  0   0  -1

In [4]:
# 2. Creando un vector de flujos de potencia
flujos = [50.0, 60.0, 70.0] # Ejemplo de flujos de potencia en MW

3-element Vector{Float64}:
 50.0
 60.0
 70.0

In [5]:
# 3. Calculo del balance de potencia en cada nodo
balance = A * flujos
display(balance)

4-element Vector{Float64}:
  50.0
  10.0
  10.0
 -70.0

In [ ]:
# 4. Resolviendo el sistema de ecuaciones para hallar los angulos nodales
B = [2.0, 2.0, 2.0, 2.0] # Ejemplo de susceptancias nodales
Y = Diagonal(B) # Matriz de susceptancias nodales
# Definiendo el vector de flujos de potencia
Pn = [100.0, -50.0, -30.0, -20.0]

θ = Y \ Pn # Resolviendo el sistema de ecuaciones (θ = inv(Y)* Pn)
println("Ángulos nodales: ", θ)

Ángulos nodales: [50.0, -25.0, -15.0, -10.0]
